theme: jekyll-theme-tactile
title: Daniel A Pinedo
description: Welcome! Click the button below to see more or contact me.

social_links  : 
  twitter     : daniel_a_pinedo
  instagram   : daniel_a_pinedo
  linkedin    : danielpinedo

gems:
  - jemoji
