theme: jekyll-theme-minimal
title: daniel pinedo
description:
url: "https://pinedo.org"
author: daniel pinedo

show_downloads: false
google_analytics: UA-119529330-1

plugins:
  - jemoji
  - jekyll-seo-tag
