theme: jekyll-theme-cayman
title: Daniel A Pinedo
description:

show_downloads: true
google_analytics: 

social-links: 
  github: dapinedo
  twitter: daniel_a_pinedo
  instagram: daniel_a_pinedo
  linkedin: danielpinedo

gems:
  - jemoji
  - jekyll-sitemap
