theme: jekyll-theme-cayman
title: Daniel Pinedo
description:
url: "https://pinedo.org"
author: Daniel Pinedo

show_downloads: false
google_analytics: UA-119529330-1

social-links: 
  github: dapinedo
  twitter: pinedo_dot_org
  linkedin: danielpinedo

plugins:
  - jemoji
  - jekyll-seo-tag
