theme: jekyll-theme-cayman
title: Daniel A Pinedo
description: Omnis ars naturae imitatio est | Art simply imitates nature | Seneca, Lucilius LXV, line 3
url: "https://pinedo.org"

show_downloads: false
google_analytics: 

social-links: 
  github: dapinedo
  twitter: daniel_a_pinedo
  instagram: daniel_a_pinedo
  linkedin: danielpinedo

plugins:
  - jemoji
  - jekyll-sitemap
