theme: jekyll-theme-minimal
title: Daniel Pinedo
description: contact
url: "https://pinedo.org"
author: Daniel Pinedo

show_downloads: false
google_analytics: UA-119529330-1

plugins:
  - jemoji
  - jekyll-seo-tag
