theme: jekyll-theme-minimal
title: Daniel A Pinedo
description:

show_downloads: false
google_analytics: 

social-links: 
  github: dapinedo
  twitter: daniel_a_pinedo
  instagram: daniel_a_pinedo
  linkedin: danielpinedo

gems:
  - jemoji
  - jekyll-sitemap
