theme: jekyll-theme-modernist
title: Daniel A Pinedo
description:

social-links  : 
  github.     : dapinedo
  twitter     : daniel_a_pinedo
  instagram   : daniel_a_pinedo
  linkedin    : danielpinedo

gems:
  - jemoji
  - jekyll-sitemap
