theme: jekyll-theme-architect
title: Daniel A Pinedo
description:

social_links  : 
  twitter     : daniel_a_pinedo
  instagram   : daniel_a_pinedo
  linkedin    : danielpinedo

gems:
  - jemoji
  - jekyll-sitemap
